const HG_IMAGES={
  compositeMain:'https://huynhgiadoor.com.vn/wp-content/uploads/2025/08/Cua-Nhua-Gia-Go-Gia-Re-HCM-2.png',
  abs:'https://huynhgiadoor.com.vn/wp-content/uploads/2025/08/Cua-Nhua-Gia-Go-Gia-Re-HCM-4.png',
  taiwan:'https://huynhgiadoor.com.vn/wp-content/uploads/2025/08/Cua-Nhua-Gia-Go-Gia-Re-HCM-3.png',
  compositeHero:'https://huynhgiadoor.com.vn/wp-content/uploads/2025/08/Cua-Nhua-Gia-Go-Gia-Re-HCM.png'
};
HG_IMAGES.fire='https://huynhgiadoor.com.vn/wp-content/uploads/2024/05/bg-dep-3.jpg';
HG_IMAGES.steel='https://huynhgiadoor.com.vn/wp-content/uploads/2024/05/slide01.jpg';
HG_IMAGES.lock='https://huynhgiadoor.com.vn/wp-content/uploads/2024/05/photo-1-1557718672558171551520.jpg';
const PRODUCTS={
 mdf:{name:'CỬA GỖ MDF',kicker:'CỬA GỖ CÔNG NGHIỆP',desc:'Dòng cửa gỗ công nghiệp dành cho không gian nội thất cần sự đồng bộ, hiện đại và tối ưu chi phí.',price:'Liên hệ báo giá',source:'Huỳnh Gia Door hiện tổ chức danh mục cửa gỗ công nghiệp gồm MDF Laminate, MDF Melamine và MDF Veneer.',gallery:[],specs:[['Bề mặt','Laminate / Melamine / Veneer'],['Ứng dụng','Phòng ngủ, căn hộ, văn phòng, khách sạn'],['Kích thước','Gia công theo ô chờ thực tế'],['Phụ kiện','Khóa, bản lề, nẹp và phụ kiện theo cấu hình']],uses:['Phòng ngủ','Căn hộ','Văn phòng','Khách sạn'],note:'Báo giá cần xác nhận theo mẫu bề mặt, kích thước, khung và phụ kiện.'},
 composite:{name:'CỬA NHỰA COMPOSITE',kicker:'CỬA NHỰA GIẢ GỖ',desc:'Cửa WPC kết hợp bột gỗ và nhựa PVC, hướng tới khả năng chống nước, chống mối mọt và đa dạng hoàn thiện.',price:'Từ khoảng 3.200.000đ/bộ',source:'Website Huỳnh Gia Door công bố nhiều cấu hình Composite: phủ da, sơn PU, sơn vân gỗ, CNC, phào nổi và cửa vòm.',gallery:[HG_IMAGES.compositeMain,HG_IMAGES.compositeHero],specs:[['Vật liệu','WPC — Wood Plastic Composite'],['Độ dày tham khảo','Khoảng 40mm'],['Hoàn thiện','Phủ da / Sơn PU / Sơn vân gỗ'],['Ứng dụng','Phòng ngủ, nhà vệ sinh, căn hộ, nhà phố, văn phòng']],uses:['Phòng ngủ','Nhà vệ sinh','Căn hộ','Nhà phố','Văn phòng','Khách sạn'],note:'Giá thay đổi theo kích thước, mẫu CNC/phào, khung, phụ kiện và điều kiện lắp đặt.'},
 abs:{name:'CỬA NHỰA ABS HÀN QUỐC',kicker:'CỬA NHỰA GIẢ GỖ',desc:'Dòng cửa nhẹ, thiết kế hiện đại, phù hợp căn hộ, phòng ngủ và văn phòng.',price:'Từ khoảng 3.800.000đ/bộ',source:'Huỳnh Gia Door giới thiệu ABS Hàn Quốc với cấu tạo nhiều lớp, bề mặt vân gỗ và trọng lượng nhẹ.',gallery:[HG_IMAGES.abs],specs:[['Cấu tạo','Deco-Sheet / ABS / PVC / LVL / Honey-Comb'],['Độ dày tham khảo','Khoảng 35mm'],['Ưu điểm','Nhẹ, chống ẩm, thiết kế hiện đại'],['Ứng dụng','Căn hộ, chung cư, phòng ngủ, văn phòng']],uses:['Căn hộ','Chung cư','Phòng ngủ','Văn phòng','Nhà phố'],note:'Giá tham khảo; cần xác nhận theo mẫu, kích thước và phụ kiện.'},
 taiwan:{name:'CỬA NHỰA ĐÀI LOAN',kicker:'CỬA NHỰA GIẢ GỖ',desc:'Giải pháp tiết kiệm với hai lựa chọn ghép thanh và đúc nguyên tấm, phù hợp nhà trọ, phòng cho thuê và nhà vệ sinh.',price:'Từ khoảng 2.700.000đ/bộ',source:'Huỳnh Gia Door công bố các cấu hình Đài Loan ghép thanh và đúc nguyên tấm.',gallery:[HG_IMAGES.taiwan],specs:[['Vật liệu','Nhựa PVC'],['Phân loại','Ghép thanh / Đúc nguyên tấm'],['Ưu điểm','Nhẹ, chống nước, chi phí tiết kiệm'],['Ứng dụng','Nhà trọ, phòng cho thuê, nhà vệ sinh, cải tạo']],uses:['Nhà trọ','Phòng cho thuê','Nhà vệ sinh','Công trình cải tạo'],note:'Giá phụ thuộc kích thước, mẫu, nẹp, khóa, bản lề và lắp đặt.'},
 fire:{name:'CỬA CHỐNG CHÁY',kicker:'GIẢI PHÁP AN TOÀN',desc:'Nhóm sản phẩm cửa chống cháy cho công trình cần giải pháp an toàn và hồ sơ kỹ thuật phù hợp.',price:'Liên hệ theo cấu hình',source:'Huỳnh Gia Door hiện có danh mục cửa gỗ chống cháy và cửa thép chống cháy.',gallery:[],specs:[['Cấu hình','Tùy loại cửa và yêu cầu công trình'],['Ứng dụng','Chung cư, văn phòng, khách sạn, công trình'],['Hồ sơ','Xác nhận theo cấu hình và yêu cầu dự án'],['Báo giá','Theo kích thước, cấp độ và phụ kiện']],uses:['Chung cư','Văn phòng','Khách sạn','Dự án'],note:'Cần xác nhận cấu hình, cấp độ chống cháy và hồ sơ áp dụng cho từng công trình.'}
};


// Mẫu sản phẩm chi tiết mở rộng — tên/mã theo danh mục hiện có trên Huỳnh Gia Door.
Object.assign(PRODUCTS, {
 'taiwan-gt25':{name:'CỬA NHỰA ĐÀI LOAN HG-GT-25',kicker:'MẪU CỬA ĐÀI LOAN',desc:'Mẫu cửa nhựa Đài Loan ghép thanh HG-GT-25 dành cho các không gian cần giải pháp nhẹ, chống nước và tối ưu chi phí.',price:'Khoảng 1.650.000đ/bộ',source:'Mẫu HG-GT-25 đang được liệt kê trong danh mục cửa nhựa Đài Loan của Huỳnh Gia Door.',gallery:[HG_IMAGES.taiwan],specs:[['Mã mẫu','HG-GT-25'],['Loại','Nhựa Đài Loan ghép thanh'],['Ứng dụng','Nhà trọ, phòng cho thuê, nhà vệ sinh'],['Giá tham khảo','1.650.000đ/bộ']],uses:['Nhà trọ','Phòng cho thuê','Nhà vệ sinh','Cải tạo'],note:'Giá tham khảo; xác nhận lại theo kích thước và phụ kiện.'},
 'taiwan-gt26':{name:'CỬA NHỰA ĐÀI LOAN HG-GT-26',kicker:'MẪU CỬA ĐÀI LOAN',desc:'Mẫu cửa ghép thanh HG-GT-26 thuộc bộ sưu tập cửa Đài Loan của Huỳnh Gia Door.',price:'Khoảng 1.650.000đ/bộ',source:'Mẫu HG-GT-26 được liệt kê trên trang chủ Huỳnh Gia Door.',gallery:[HG_IMAGES.taiwan],specs:[['Mã mẫu','HG-GT-26'],['Loại','Nhựa Đài Loan ghép thanh'],['Ưu điểm','Nhẹ, chống nước, tiết kiệm'],['Giá tham khảo','1.650.000đ/bộ']],uses:['Nhà trọ','Nhà vệ sinh','Phòng cho thuê'],note:'Cần xác nhận mẫu và kích thước thực tế trước khi chốt.'},
 'taiwan-gt27':{name:'CỬA NHỰA ĐÀI LOAN HG-GT-27',kicker:'MẪU CỬA ĐÀI LOAN',desc:'Mẫu cửa HG-GT-27 được Huỳnh Gia Door niêm yết trong nhóm cửa nhựa Đài Loan ghép thanh.',price:'Khoảng 1.650.000đ/bộ',source:'Mẫu HG-GT-27 hiện xuất hiện trong danh mục sản phẩm trên website Huỳnh Gia Door.',gallery:[HG_IMAGES.taiwan],specs:[['Mã mẫu','HG-GT-27'],['Loại','Nhựa Đài Loan ghép thanh'],['Giá tham khảo','1.650.000đ/bộ'],['Ứng dụng','Nhà vệ sinh, phòng cho thuê, công trình cải tạo']],uses:['Nhà vệ sinh','Phòng cho thuê','Công trình cải tạo'],note:'Giá có thể thay đổi theo cấu hình hoàn thiện.'},
 'taiwan-gt28':{name:'CỬA NHỰA ĐÀI LOAN HG-GT-28',kicker:'MẪU CỬA ĐÀI LOAN',desc:'Mẫu HG-GT-28 thuộc dòng cửa nhựa Đài Loan ghép thanh, hướng đến giải pháp kinh tế cho công trình.',price:'Khoảng 1.650.000đ/bộ',source:'Mẫu HG-GT-28 được liệt kê trên website Huỳnh Gia Door.',gallery:[HG_IMAGES.taiwan],specs:[['Mã mẫu','HG-GT-28'],['Loại','Nhựa Đài Loan ghép thanh'],['Giá tham khảo','1.650.000đ/bộ'],['Ứng dụng','Nhà trọ, phòng cho thuê, nhà vệ sinh']],uses:['Nhà trọ','Phòng cho thuê','Nhà vệ sinh'],note:'Liên hệ để xác nhận kích thước và phụ kiện.'},
 'taiwan-gt29':{name:'CỬA NHỰA ĐÀI LOAN HG-GT-29',kicker:'MẪU CỬA ĐÀI LOAN',desc:'Mẫu HG-GT-29 trong bộ sưu tập cửa Đài Loan của Huỳnh Gia Door.',price:'Khoảng 1.650.000đ/bộ',source:'Mẫu HG-GT-29 được liệt kê trong danh mục sản phẩm hiện tại.',gallery:[HG_IMAGES.taiwan],specs:[['Mã mẫu','HG-GT-29'],['Loại','Nhựa Đài Loan ghép thanh'],['Giá tham khảo','1.650.000đ/bộ'],['Ứng dụng','Phòng cho thuê, nhà vệ sinh']],uses:['Phòng cho thuê','Nhà vệ sinh','Cải tạo'],note:'Giá tham khảo theo danh mục hiện tại.'},
 'taiwan-gt30':{name:'CỬA NHỰA ĐÀI LOAN HG-GT-30',kicker:'MẪU CỬA ĐÀI LOAN',desc:'Mẫu HG-GT-30 thuộc dòng cửa nhựa Đài Loan ghép thanh.',price:'Liên hệ báo giá',source:'Mẫu HG-GT-30 hiện được liệt kê trên website Huỳnh Gia Door.',gallery:[HG_IMAGES.taiwan],specs:[['Mã mẫu','HG-GT-30'],['Loại','Nhựa Đài Loan ghép thanh'],['Ứng dụng','Nhà trọ, phòng cho thuê, nhà vệ sinh'],['Báo giá','Theo kích thước và cấu hình']],uses:['Nhà trọ','Phòng cho thuê','Nhà vệ sinh'],note:'Liên hệ để nhận báo giá theo kích thước thực tế.'},
 'composite-sya216':{name:'CỬA COMPOSITE SYA 216',kicker:'CỬA NHỰA COMPOSITE',desc:'Mẫu cửa Composite SYA 216 thuộc nhóm cửa nhựa giả gỗ Composite của Huỳnh Gia Door.',price:'Liên hệ báo giá',source:'Mã SYA 216 hiện được liệt kê trong danh mục Composite của Huỳnh Gia Door.',gallery:[HG_IMAGES.compositeMain,HG_IMAGES.compositeHero],specs:[['Mã mẫu','SYA 216'],['Vật liệu','WPC / Composite'],['Hoàn thiện','Theo mẫu thực tế'],['Ứng dụng','Phòng ngủ, nhà vệ sinh, căn hộ']],uses:['Phòng ngủ','Nhà vệ sinh','Căn hộ','Nhà phố'],note:'Liên hệ để chọn màu, mẫu bề mặt và phụ kiện.'},
 'composite-sya203':{name:'CỬA COMPOSITE SYA 203',kicker:'CỬA NHỰA COMPOSITE',desc:'Mẫu cửa Composite SYA 203 dành cho khách hàng cần bề mặt hiện đại và khả năng chống ẩm tốt.',price:'Liên hệ báo giá',source:'Mã SYA 203 hiện được liệt kê trong danh mục Composite của Huỳnh Gia Door.',gallery:[HG_IMAGES.compositeMain,HG_IMAGES.compositeHero],specs:[['Mã mẫu','SYA 203'],['Vật liệu','WPC / Composite'],['Hoàn thiện','Sơn / bề mặt theo mẫu'],['Ứng dụng','Phòng ngủ, căn hộ, nhà phố']],uses:['Phòng ngủ','Căn hộ','Nhà phố'],note:'Giá phụ thuộc kích thước và cấu hình hoàn thiện.'},
 'composite-sya115':{name:'CỬA COMPOSITE SYA 115',kicker:'CỬA NHỰA COMPOSITE',desc:'Mẫu cửa Composite SYA 115 thuộc nhóm sản phẩm cửa nhựa giả gỗ của Huỳnh Gia Door.',price:'Liên hệ báo giá',source:'Mã SYA 115 hiện được liệt kê trong danh mục Composite trên website.',gallery:[HG_IMAGES.compositeMain,HG_IMAGES.compositeHero],specs:[['Mã mẫu','SYA 115'],['Vật liệu','WPC / Composite'],['Ưu điểm','Chống ẩm, đa dạng hoàn thiện'],['Ứng dụng','Nội thất nhà ở và công trình']],uses:['Nhà ở','Căn hộ','Khách sạn','Văn phòng'],note:'Liên hệ để xác nhận mẫu và báo giá.'},
 'composite-flat2':{name:'CỬA COMPOSITE TRƠN PHẲNG 2',kicker:'CỬA NHỰA COMPOSITE',desc:'Mẫu cửa Composite trơn phẳng 2, thiết kế tối giản cho không gian nội thất hiện đại.',price:'Khoảng 4.000.000đ/bộ',source:'Mẫu cửa Composite trơn phẳng 2 hiện được Huỳnh Gia Door niêm yết trên website.',gallery:[HG_IMAGES.compositeMain,HG_IMAGES.compositeHero],specs:[['Mẫu','Trơn phẳng 2'],['Vật liệu','WPC / Composite'],['Giá tham khảo','4.000.000đ/bộ'],['Ứng dụng','Phòng ngủ, nhà vệ sinh, căn hộ']],uses:['Phòng ngủ','Nhà vệ sinh','Căn hộ'],note:'Giá tham khảo theo danh mục; xác nhận lại theo cấu hình.'},
 'fire-vs01':{name:'CỬA CHỐNG CHÁY VS01',kicker:'GIẢI PHÁP AN TOÀN',desc:'Mẫu cửa chống cháy VS01 được liệt kê trong danh mục cửa chống cháy của Huỳnh Gia Door.',price:'Khoảng 2.599.999đ/bộ',source:'Mẫu VS01 hiện được liệt kê trên trang chủ Huỳnh Gia Door; cấu hình thực tế cần xác nhận theo yêu cầu công trình.',gallery:[],specs:[['Mã mẫu','VS01'],['Loại','Cửa chống cháy'],['Ứng dụng','Công trình, chung cư, văn phòng, khách sạn'],['Báo giá','Theo cấu hình và yêu cầu kỹ thuật']],uses:['Chung cư','Văn phòng','Khách sạn','Dự án'],note:'Cần xác nhận cấp độ chống cháy và hồ sơ kỹ thuật cho từng công trình.'},
 'steel-sgd15':{name:'CỬA THÉP VÂN GỖ SGD 15',kicker:'CỬA THÉP VÂN GỖ',desc:'Mẫu cửa thép vân gỗ SGD 15 được Huỳnh Gia Door liệt kê trong nhóm sản phẩm cửa thép.',price:'Khoảng 2.599.999đ/bộ',source:'Mã SGD 15 hiện xuất hiện trên trang chủ Huỳnh Gia Door.',gallery:[],specs:[['Mã mẫu','SGD 15'],['Loại','Cửa thép vân gỗ'],['Giá tham khảo','2.599.999đ/bộ'],['Ứng dụng','Nhà ở và công trình']],uses:['Nhà phố','Căn hộ','Công trình'],note:'Giá tham khảo; cần xác nhận kích thước và phụ kiện.'},
 'steel-sgd16':{name:'CỬA THÉP VÂN GỖ SGD 16',kicker:'CỬA THÉP VÂN GỖ',desc:'Mẫu cửa thép vân gỗ SGD 16 với thiết kế hướng đến độ bền và vẻ ngoài mô phỏng vân gỗ.',price:'Khoảng 2.599.999đ/bộ',source:'Mã SGD 16 hiện xuất hiện trong danh mục sản phẩm Huỳnh Gia Door.',gallery:[],specs:[['Mã mẫu','SGD 16'],['Loại','Cửa thép vân gỗ'],['Giá tham khảo','2.599.999đ/bộ'],['Ứng dụng','Nhà phố, căn hộ, công trình']],uses:['Nhà phố','Căn hộ','Công trình'],note:'Giá tham khảo theo website; xác nhận lại trước khi đặt.'},
 'steel-sgd17':{name:'CỬA THÉP VÂN GỖ SGD 17',kicker:'CỬA THÉP VÂN GỖ',desc:'Mẫu cửa thép vân gỗ SGD 17 thuộc nhóm cửa thép vân gỗ của Huỳnh Gia Door.',price:'Khoảng 2.599.999đ/bộ',source:'Mã SGD 17 hiện được liệt kê trên trang chủ Huỳnh Gia Door.',gallery:[],specs:[['Mã mẫu','SGD 17'],['Loại','Cửa thép vân gỗ'],['Giá tham khảo','2.599.999đ/bộ'],['Ứng dụng','Nhà phố, công trình']],uses:['Nhà phố','Công trình','Văn phòng'],note:'Liên hệ để xác nhận mẫu và cấu hình.'},
 'steel-sgd18':{name:'CỬA THÉP VÂN GỖ SGD 18',kicker:'CỬA THÉP VÂN GỖ',desc:'Mẫu cửa thép vân gỗ SGD 18 được liệt kê trong nhóm sản phẩm cửa thép của Huỳnh Gia Door.',price:'Khoảng 2.599.999đ/bộ',source:'Mã SGD 18 hiện xuất hiện trong danh mục sản phẩm hiện tại.',gallery:[],specs:[['Mã mẫu','SGD 18'],['Loại','Cửa thép vân gỗ'],['Giá tham khảo','2.599.999đ/bộ'],['Ứng dụng','Nhà phố, căn hộ, công trình']],uses:['Nhà phố','Căn hộ','Công trình'],note:'Giá tham khảo; xác nhận lại theo kích thước và phụ kiện.'},
 'lock-kassler-kl393':{name:'KHÓA ĐIỆN TỬ KASSLER KL-393',kicker:'PHỤ KIỆN CỬA',desc:'Khóa điện tử Kassler KL-393 được Huỳnh Gia Door liệt kê trong nhóm phụ kiện cửa.',price:'Khoảng 4.190.000đ',source:'Mẫu Kassler KL-393 hiện xuất hiện trong danh mục sản phẩm trên website Huỳnh Gia Door.',gallery:[],specs:[['Mã mẫu','Kassler KL-393'],['Nhóm','Khóa điện tử'],['Giá tham khảo','4.190.000đ'],['Ứng dụng','Cửa phòng, căn hộ, nhà phố']],uses:['Căn hộ','Nhà phố','Phòng ngủ','Văn phòng'],note:'Xác nhận màu, cấu hình và khả năng tương thích với bộ cửa trước khi đặt.'}
});


/* V10.12 — Mẫu cửa thực tế từ bộ ảnh người dùng cung cấp. Không dùng ảnh minh họa thay thế. */
const HGD_SAMPLE_DOORS = [];
for (let i=1;i<=18;i++){
  const n=String(i).padStart(2,'0');
  HGD_SAMPLE_DOORS.push({slug:`composite-${n}`,name:`MẪU COMPOSITE ${n}`,kicker:'CỬA NHỰA COMPOSITE',category:'COMPOSITE',image:`assets/door-samples/composite/composite-${n}.png`,gallery:[`assets/door-samples/composite/composite-${n}.png`]});
  PRODUCTS[`composite-${n}`]={name:`CỬA NHỰA COMPOSITE — MẪU ${n}`,kicker:'CỬA NHỰA COMPOSITE',desc:`Mẫu cửa Composite số ${n} trong bộ sưu tập mẫu cửa tiêu biểu của Huỳnh Gia Door.`,price:'Liên hệ báo giá',source:'Ảnh mẫu được lấy từ bộ ảnh mẫu cửa Composite do người dùng cung cấp.',gallery:[`assets/door-samples/composite/composite-${n}.png`],specs:[['Mã mẫu',`COMPOSITE-${n}`],['Loại','Cửa nhựa Composite'],['Hình ảnh','Mẫu thực tế'],['Báo giá','Theo kích thước và cấu hình']],uses:['Phòng ngủ','Nhà vệ sinh','Căn hộ','Nhà phố'],note:'Liên hệ Huỳnh Gia Door để xác nhận kích thước, màu, cấu hình và phụ kiện.'};
}
for (let i=1;i<=13;i++){
  const n=String(i).padStart(2,'0');
  const ext=i===13?'jpg':'png';
  HGD_SAMPLE_DOORS.push({slug:`composite-vom-${n}`,name:`MẪU COMPOSITE VÒM ${n}`,kicker:'CỬA COMPOSITE VÒM',category:'COMPOSITE VÒM',image:`assets/door-samples/composite-vom/composite-vom-${n}.${ext}`,gallery:[`assets/door-samples/composite-vom/composite-vom-${n}.${ext}`]});
  PRODUCTS[`composite-vom-${n}`]={name:`CỬA COMPOSITE VÒM — MẪU ${n}`,kicker:'CỬA COMPOSITE VÒM',desc:`Mẫu cửa Composite vòm số ${n} trong bộ sưu tập mẫu cửa tiêu biểu của Huỳnh Gia Door.`,price:'Liên hệ báo giá',source:'Ảnh mẫu được lấy từ bộ ảnh Composite vòm do người dùng cung cấp.',gallery:[`assets/door-samples/composite-vom/composite-vom-${n}.${ext}`],specs:[['Mã mẫu',`COMPOSITE-VOM-${n}`],['Loại','Cửa Composite vòm'],['Hình ảnh','Mẫu thực tế'],['Báo giá','Theo kích thước và cấu hình']],uses:['Phòng ngủ','Căn hộ','Nhà phố','Công trình'],note:'Liên hệ Huỳnh Gia Door để xác nhận kích thước vòm, cấu hình, màu và phụ kiện.'};
}
PRODUCTS.composite.gallery = HGD_SAMPLE_DOORS.filter(x=>x.category==='COMPOSITE').map(x=>x.image);
PRODUCTS['composite-vom']={name:'CỬA COMPOSITE VÒM',kicker:'BỘ SƯU TẬP MẪU VÒM',desc:'Bộ sưu tập các mẫu cửa Composite vòm được dùng làm mẫu tham khảo trên website.',price:'Liên hệ báo giá',source:'Ảnh mẫu được lấy từ bộ ảnh Composite vòm do người dùng cung cấp.',gallery:HGD_SAMPLE_DOORS.filter(x=>x.category==='COMPOSITE VÒM').map(x=>x.image),specs:[['Số mẫu','13 mẫu'],['Loại','Cửa Composite vòm'],['Hình ảnh','Mẫu thực tế'],['Báo giá','Theo từng kích thước và cấu hình']],uses:['Phòng ngủ','Căn hộ','Nhà phố','Công trình'],note:'Liên hệ để xác nhận mẫu vòm, kích thước, màu và phụ kiện.'};
